#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config focus_follows_pointer true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 5

#Autostart
sxhkd &
picom --config /home/suzuya/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
nm-applet &
blueman-applet
